config/routes.rb
Rails.application.routes.draw do
  get 'admin_ordered_products/index'
  
  get 'shipping_addresses/index'
  get 'shipping_addresses/edit'
  get 'orders/new'
  get 'orders/index'
  get 'orders/show'
  get 'orders/confirm'
  get 'orders/complete'
  get 'cart_items/index'
  get 'admin_products/index'
  get 'admin_products/new'
  get 'admin_products/show'
  get 'admin_products/edit'
  devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :cart_items,except:[:new,:edit,:show]
  post "cart_items/add_item" => "cart_items#add_item"
  delete "cart_items/:id" => "cart_items#destroy"
  resources :orders,only:[:new,:create,:index,:show]
  post "orders/confirm" => "orders#confirm"
  post "orders" => "orders#create"
  get "orders/complete" => "orders#complete"
  resources :admin_ordered_products, only:[:index,:show]
  patch "admin_ordered_products/:id/order_update" => "admin_ordered_products#order_update", as: 'order_update'
  patch "admin_ordered_products/:id/production_update" => "admin_ordered_products#production_update"
  resources :admin_products,except:[:destroy]
  resources :products,only: [:index,:show]
  resources :shipping_address,only:[:index,:create,:edit,:update]
  get "admins/top" => "admins#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :administrator do
    resources :users, only: [:index]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, optional: true
    has_many :shipping_addresses, dependent: :destroy
    has_many :ordered_products, dependent: :destroy
    enum pay_method: { クレジットカード: 1, 銀行振り込み: 2 }
    
    enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
    enum production_status: { 着手不可: 0, 制作待ち: 1, 製作中: 2, 制作完了: 3 }
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :admin, optional: true
    has_many :ordered_product, dependent: :destroy
    attachment :image
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :order
    def abc
        zipcode + address + name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders, dependent: :destroy
end

app/controllers/admin_ordered_products_controller.rb
class AdminOrderedProductsController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    
  end

  def order_update
   @order = Order.find(params[:id])
   @order.update(admin_ordered_products_params)
   redirect_to admin_ordered_product_path(@order)
  end

  def production_update
  end

  private
    def admin_ordered_products_params
      params.require(:order).permit(:order_status)
    end
end

app/controllers/admin_products_controller.rb
class AdminProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admin_products_path
  end

  def show
  end

  def edit
  end

  private
    def product_params
      params.require(:product).permit(:name, :explain, :notax_price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  


    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :family_name, :zipcode)}
      end

      
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end

  def add_item
    @cart_item = CartItem.new(cart_item_params)
    @user_id = current_user
    @product_id = 
    @cart_item.save
    redirect_to cart_items_index_path
  end



  private
    def cart_item_params
      params.require(:cart_items).permit(user_id, :product_id, :number)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @user = current_user 
end

def create
    @order = Order.new(order_params)
    @order.user_id =current_user.id
    @order.save
    redirect_to orders_complete_path
end

def index
  @orders = Order.all
  
end

def show
  @order = Order.find(params[:id])
end

def confirm
    @order = Order.new(order_params)
    @order2 = Order.find_by(id: params[:format])
    @ordered_products = OrderedProduct.all
    @order.billing_amount = 0
    @ordered_products.each do |ordered_product|
      @order.billing_amount += (ordered_product.product.notax_price.to_i * ordered_product.number.to_i)
    end
end

def complete
end


private
    def order_params
        params.require(:order).permit(:user_id, :delivery_address, :pay_method, :delivery_zipcode, :address_name, :deliver)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end
end

app/controllers/shipping_address_controller.rb
class ShippingAddressController < ApplicationController
    def index
        @shipping_address = ShippingAddress.new
        @shipping_addresses = ShippingAddress.all
      end
    
      def create
        @shipping_address = ShippingAddress.new(shipping_address_params)
        @shipping_address.save
        redirect_to shipping_address_index_path
      end
    
      def edit
      end
    
      private
        def shipping_address_params
          params.require(:shipping_address).permit(:zipcode, :address, :name)
        end
end

app/helpers/admin_ordered_products_helper.rb
module AdminOrderedProductsHelper
end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_address_helper.rb
module ShippingAddressHelper
end

app/views/admin_ordered_products/index.html.erb
<h3>注文履歴一覧</h3>
<table class="table table-bordered">
    <thead>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
            <tr>
                <td><%= link_to admin_ordered_product_path(order) do %>
                    <%= order.created_at.strftime('%Y/%m/%d') %>
                <% end %></td>
                <td><%= order.user.family_name %><%= order.user.middle_name %></td>
                <td></td>
                <td><%= order.order_status %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin_ordered_products/show.html.erb
<div class="container">
    <div class="row">
        <h3>注文履歴詳細</h3>
        <span>購入者</span>
        <%= @order.user.family_name %><%= @order.user.middle_name %><br>
        <span>配送先</span>
        <%= @order.user.zipcode %><%= @order.user.address %><br>
        <%= @order.user.name %>
        <span>支払方法</span>
        <%= @order.pay_method %><br>
        <span>注文ステータス</span>
        <%= form_for @order, url:  order_update_path(@order) do |f| %>
        <%= f.select :order_status,Order.order_statuses.keys.to_a, {} %>
        <%= f.submit "更新" %>
        <% end %>
    </div>
    <div class="row">
        <div class="col-xs-9">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>商品名</th>
                        <th>単価（税込）</th>
                        <th>数量</th>
                        <th>小計</th>
                        <th>制作ステータス</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            
                            <%= select :production_status,:name,OrderedProduct.production_statuses.keys.to_a %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xs-3">
            <table>
                <tr>
                    <th>商品合計</th>
                    <td></td>
                </tr>
                <tr>
                    <th>送料</th>
                    <td></td>
                </tr>
                <tr>
                    <th>請求額合計</th>
                    <td></td>
                </tr>
            </table>
        </div>
</div>

app/views/admin_products/edit.html.erb
<h1>AdminProducts#edit</h1>
<p>Find me in app/views/admin_products/edit.html.erb</p>

app/views/admin_products/index.html.erb
<h3>商品一覧</h3>
<table>
    <thead>
        <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
        </tr>
    </thead>
    <tbody>
        
            <% @products.each do |product| %>
                <tr>
                    <td><%= product.id %></td>
                    <td><%= product.name %></td>
                    <td><%= product.notax_price %></td>
                    <td></td>
                    <td></td>
                </tr>
            <% end %>
    </tbody>
</table>

<%= link_to "ログアウト", user_registration_path, method: :delete %>

app/views/admin_products/new.html.erb
<h3>商品新規登録</h3>

<%= form_for @product, url: admin_products_path do |f| %>
    <%= f.attachment_field :image %>
    <span>商品名</span>
    <%= f.text_field :name %>
    <span>商品説明</span>
    <%= f.text_area :explain %>
    <span>税抜価格</span>
    <%= f.text_field :notax_price %>
    <span>円</span>
    <%= f.submit "新規登録" %>
<% end %>

app/views/admin_products/show.html.erb
<h1>AdminProducts#show</h1>
<p>Find me in app/views/admin_products/show.html.erb</p>

app/views/shipping_address/index.html.erb
<%= form_for @shipping_address, url:shipping_address_index_path do |f| %>
    郵便
    <%= f.number_field :zipcode %>
    住所
    <%= f.text_field :address %>
    宛名
    <%= f.text_field :name %>
    <%= f.submit "登録する" %>
<% end %>

<% @shipping_addresses.each do |shipping_address| %>
    <%= shipping_address.zipcode %>
    <%= shipping_address.address %>
    <%= shipping_address.name %>
<% end %>