config/routes.rb
Rails.application.routes.draw do
  get 'admin_ordered_products/index'
  
  get 'shipping_addresses/index'
  get 'shipping_addresses/edit'
  get 'orders/new'
  get 'orders/index'
  get 'orders/show'
  get 'orders/confirm'
  get 'orders/complete'
  get 'cart_items/index'
  get 'admin_products/index'
  get 'admin_products/new'
  get 'admin_products/show'
  get 'admin_products/edit'
  devise_for :admins, controllers: {
  sessions: 'admins/sessions',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  resources :cart_items,except:[:new,:edit,:show]
  post "cart_items/add_item" => "cart_items#add_item"
  delete "cart_items/:id" => "cart_items#destroy"
  resources :orders,only:[:new,:create,:index,:show]
  post "orders/confirm" => "orders#confirm"
  post "orders" => "orders#create"
  get "orders/complete" => "orders#complete"
  resources :admin_ordered_products, only:[:index,:show]
  patch "admin_ordered_products/:id/order_update" => "admin_ordered_products#order_update", as: 'order_update'
  patch "admin_ordered_products/:id/production_update" => "admin_ordered_products#production_update"
  resources :admin_products,except:[:destroy]
  resources :products,only: [:index,:show]
  resources :shipping_address,only:[:index,:create,:edit,:update]
  get "admins/top" => "admins#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :administrator do
    resources :users, only: [:index]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, optional: true
    has_many :shipping_addresses, dependent: :destroy
    has_many :ordered_products, dependent: :destroy
    enum pay_method: { クレジットカード: 1, 銀行振り込み: 2 }
    
    enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
    enum production_status: { 着手不可: 0, 制作待ち: 1, 製作中: 2, 制作完了: 3 }
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :admin, optional: true
    has_many :ordered_product, dependent: :destroy
    attachment :image
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :order
    def abc
        zipcode + address + name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders, dependent: :destroy
end

app/controllers/admin_ordered_products_controller.rb
class AdminOrderedProductsController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    
  end

  def order_update
   @order = Order.find(params[:id])
   @order.update(admin_ordered_products_params)
   redirect_to admin_ordered_product_path(@order)
  end

  def production_update
  end

  private
    def admin_ordered_products_params
      params.require(:order).permit(:order_status)
    end
end

app/controllers/admin_products_controller.rb
class AdminProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admin_products_path
  end

  def show
  end

  def edit
  end

  private
    def product_params
      params.require(:product).permit(:name, :explain, :notax_price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  


    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :family_name, :zipcode)}
      end

      
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end

  def add_item
    @cart_item = CartItem.new(cart_item_params)
    @user_id = current_user
    @product_id = 
    @cart_item.save
    redirect_to cart_items_index_path
  end



  private
    def cart_item_params
      params.require(:cart_items).permit(user_id, :product_id, :number)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @user = current_user 
end

def create
    @order = Order.new(order_params)
    @order.user_id =current_user.id
    @order.save
    redirect_to orders_complete_path
end

def index
  @orders = Order.all
  
end

def show
  @order = Order.find(params[:id])
end

def confirm
    @order = Order.new(order_params)
    @order2 = Order.find_by(id: params[:format])
    @ordered_products = OrderedProduct.all
    @order.billing_amount = 0
    @ordered_products.each do |ordered_product|
      @order.billing_amount += (ordered_product.product.notax_price.to_i * ordered_product.number.to_i)
    end
end

def complete
end


private
    def order_params
        params.require(:order).permit(:user_id, :delivery_address, :pay_method, :delivery_zipcode, :address_name, :deliver)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end
end

app/controllers/shipping_address_controller.rb
class ShippingAddressController < ApplicationController
    def index
        @shipping_address = ShippingAddress.new
        @shipping_addresses = ShippingAddress.all
      end
    
      def create
        @shipping_address = ShippingAddress.new(shipping_address_params)
        @shipping_address.save
        redirect_to shipping_address_index_path
      end
    
      def edit
      end
    
      private
        def shipping_address_params
          params.require(:shipping_address).permit(:zipcode, :address, :name)
        end
end

app/helpers/admin_ordered_products_helper.rb
module AdminOrderedProductsHelper
end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/helpers/administrator/users_helper.rb
module Administrator::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_address_helper.rb
module ShippingAddressHelper
end

app/views/cart_items/index.html.erb
<h1>CartItems#index</h1>
<p>Find me in app/views/cart_items/index.html.erb</p>

app/views/orders/complete.html.erb
注文ありがとうございます

app/views/orders/confirm.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-7">
            <%= form_for @order,url: orders_path do |f| %>
            <h2>注文情報確認</h2>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>商品名</th>
                        <th>単価（税込）</th>
                        <th>数量</th>
                        <th>小計</th>
                    </tr>
                </thead>
                <tbody>
                    <% @ordered_products.each do |ordered_product| %>
                    <tr>
                        <td><%= ordered_product.product.name %></td>
                        <td><%= ordered_product.product.notax_price %></td>
                        <td><%= ordered_product.number %></td>
                        <td><%= ordered_product.product.notax_price.to_i * ordered_product.number.to_i %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-xs-4">
            <table class="table table-bordered">
                <tr>
                    <th>送料</th>
                    <td>800</td>
                </tr>
                <tr>
                    <th>商品合計</th>
                    <td><%= @order.billing_amount %></td>
                </tr>
                <tr>
                    <th>請求金額</th>
                    <td><%= @order.billing_amount.to_i + 800 %></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
            <h2>支払い方法</h2>
            <%= @order.pay_method %>
            <h2>お届け先</h2>
            <%= @order2 %>
            <%= @order.deliver %><br>
            <%= f.hidden_field :delivery_zipcode %>
            <%= @order.delivery_zipcode %><br>
            <%= f.hidden_field :delivery_address %>
            <%= @order.delivery_address %><br>
            <%= f.hidden_field :address_name %>
            <%= @order.address_name %><br>
            <%= f.submit "購入を確定する" %>
            <% end %>
    </div>
</div>

app/views/orders/index.html.erb
<h3>注文履歴一覧</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
        </tr>
    </thead>
    <tbody>
        
            <% @orders.each do |order| %>
                <tr>
                    <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                    <td><%= order.delivery_zipcode %><%= order.delivery_address %><%= order.address_name %></td>
                    <td></td>
                    <td><%= order.billing_amount %></td>
                    <td><%= order.order_status %></td>
                    <td><%= link_to "表示する",order_path(order) %> </td>
                </tr>
            <% end %>
    </tbody>
</table>

app/views/orders/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <%= form_for @order, url: orders_confirm_path  do |f| %>
                <h3>注文情報入力</h3>
                <h3>支払い方法</h3>
                <%= f.radio_button :pay_method, "クレジットカード", label: "クレジットカード" %>クレジットカード<br>
                <%= f.radio_button :pay_method, "銀行振り込み", label: "銀行振り込み" %>銀行振り込み
            

            
                <h2>お届け先</h2>
                <label><%= f.radio_button :deliver, @user.zipcode+@user.address+@user.family_name+@user.middle_name %>ご自身の住所</label><br>
                <%= @user.zipcode %><br>
                <%= @user.address %><br>
                <%= @user.family_name %>
                <%= @user.middle_name %><br>

                <label><%= f.radio_button :deliver, "登録済住所から選択" %>登録済住所から選択</label><br>
                <%= select_tag :shipping_address_id, options_from_collection_for_select(ShippingAddress.all, :id, :abc) %><br>
                <label><%= f.radio_button :deliver, "新しいお届け先" %>新しいお届け先</label><br>
                <%= f.label :delivery_zipcode, "郵便番号（ハイフンなし）" %>
                <%= f.number_field :delivery_zipcode %><br>
                <%= f.label :delivery_address, "住所" %>
                <%= f.text_field :delivery_address %><br>
                <%= f.label :address_name, "宛名" %>
                <%= f.text_field :address_name %><br>
                <%= f.submit "確認画面へ進む" %>
            <% end %>
        </div>
    </div>
</div>

app/views/orders/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-8">
            <h3>注文履歴詳細</h3>
            <p>注文情報<p>
            <table class="table table-bordered">
                <tr>
                    <th>注文日</th>
                    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
                </tr>
                <tr>
                    <th>配送先</th>
                    <td><%= @order.delivery_zipcode %><%= @order.delivery_address %><%= @order.address_name %></td>
                </tr>
                <tr>
                    <th>支払方法</th>
                    <td><%= @order.pay_method %></td>
                </tr>
                <tr>
                    <th>ステータス</th>
                    <td></td>
                </tr>
            </table>
        </div>
        <div class="col-xs-4">
            <p>請求情報</p>
            <table class="table table-bordered">
                <tr>
                    <th>商品合計</th>
                    <td></td>
                </tr>
                <tr>
                    <th>配送料</th>
                    <td></td>
                </tr>
                <tr>
                    <th>ご請求額</th>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
        <div class="row">
            <p>注文内容</p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>商品</th>
                        <th>単価（税込）</th>
                        <th>個数</th>
                        <th>小計</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<h2>商品一覧</h2>
<% @products.each do |product| %>
    <%= attachment_image_tag product, :image %>
    <%= product.name %>
    <%= product.notax_price %>
<% end %>

app/views/products/show.html.erb
<%= @product.name %>
<%= @product.explain %>
<%= @product.notax_price %>
<%= link_to "カートに入れる", cart_items_add_item_path, method: :post %>